# Generated by Django 6.1 on 2026-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0010_courseexecution_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexecution',
            name='used_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
