# Generated by Django 6.1 on 2026-08-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0011_courseexecution_used_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainanswer',
            name='current_state_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_state_answers', to='teumteum.option'),
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='next_schedule_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_schedule_answers', to='teumteum.option'),
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='next_schedule_other_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
