# Generated by Django 6.1 on 2026-08-17

from django.db import migrations


def create_next_schedule_and_state_questions(apps, schema_editor):
    Question = apps.get_model("teumteum", "Question")
    Option = apps.get_model("teumteum", "Option")

    # 세 번째 질문: 다음 일정
    q3 = Question.objects.create(
        question_id=3,
        title="다음 일정은 무엇인가요?",
        description="다음 일정 전까지 딱 맞게 끝나는 코스를 준비할게요 :)"
    )

    # 네 번째 질문: 현재 상태
    q4 = Question.objects.create(
        question_id=4,
        title="지금 당신의 상태는 어떤가요?",
        description="지금 상태에 맞는 회복을 도와드릴게요 :)"
    )

    # 세 번째 질문 선택지
    Option.objects.create(option_id=9, question=q3, content="수업·회의")
    Option.objects.create(option_id=10, question=q3, content="친구·약속")
    Option.objects.create(option_id=11, question=q3, content="업무·과제")
    Option.objects.create(option_id=12, question=q3, content="귀가·휴식")
    Option.objects.create(option_id=13, question=q3, content="기타")
    Option.objects.create(option_id=14, question=q3, content="없음")

    # 네 번째 질문 선택지
    Option.objects.create(option_id=15, question=q4, content="피곤해요")
    Option.objects.create(option_id=16, question=q4, content="긴장돼요")
    Option.objects.create(option_id=17, question=q4, content="복잡해요")
    Option.objects.create(option_id=18, question=q4, content="몸이 뻐근해요")
    Option.objects.create(option_id=19, question=q4, content="피부가 신경 쓰여요")


def remove_next_schedule_and_state_questions(apps, schema_editor):
    Question = apps.get_model("teumteum", "Question")
    Question.objects.filter(question_id__in=[3, 4]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0012_main_answer_next_schedule_and_state'),
    ]

    operations = [
        migrations.RunPython(
            create_next_schedule_and_state_questions,
            remove_next_schedule_and_state_questions,
        ),
    ]
