# Generated by Django 6.1 on 2026-08-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0013_next_schedule_and_state_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainanswer',
            name='current_state_option',
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='current_state_options',
            field=models.ManyToManyField(related_name='current_state_answers', to='teumteum.option'),
        ),
    ]
