# Generated by Django 6.1 on 2026-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0014_main_answer_current_state_multi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseexecution',
            name='used_minutes',
        ),
        migrations.AddField(
            model_name='courseexecution',
            name='used_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
