# Generated by Django 6.1 on 2026-08-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0015_course_execution_used_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModuleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('voice_script', models.TextField(blank=True, null=True)),
                ('steps', models.JSONField(blank=True, default=list, null=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('question_options', models.JSONField(blank=True, default=list, null=True)),
                ('allow_text_input', models.BooleanField(default=False)),
                ('estimated_minutes', models.IntegerField()),
                ('tags', models.JSONField(default=list)),
                ('allowed_contexts', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'activity_module_templates',
            },
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='allow_text_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='question_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='steps',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='voice_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
