# Generated by Django 6.1 on 2026-08-17

from django.db import migrations

# 장소 옵션(teumteum Question 1)과 동일한 텍스트만 사용. 빈 리스트는 장소 무관.
ALL_CONTEXTS = ["길거리", "대중교통", "카페", "기타"]


def create_activity_module_templates(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")

    ActivityModuleTemplate.objects.create(
        content_type="audio_guide",
        title="2분 눈·호흡 리셋",
        description="화면에서 잠시 눈을 떼고 호흡에 집중하는 짧은 리셋입니다.",
        voice_script="화면에서 시선을 잠시 떼고, 4초간 천천히 들이마셔 보세요.",
        steps=[
            {"phase": "들이마시기", "duration_seconds": 4},
            {"phase": "내쉬기", "duration_seconds": 6},
        ],
        estimated_minutes=2,
        tags=["피곤해요", "긴장돼요"],
        allowed_contexts=ALL_CONTEXTS,
    )

    ActivityModuleTemplate.objects.create(
        content_type="audio_guide",
        title="약속 전 긴장 리셋",
        description="약속을 앞두고 긴장을 가라앉히는 짧은 호흡 가이드입니다.",
        voice_script="오늘의 약속을 잘 해내야 한다는 생각을 잠시 내려놓아도 괜찮아요.",
        steps=[
            {"phase": "들이마시기", "duration_seconds": 4},
            {"phase": "내쉬기", "duration_seconds": 6},
        ],
        estimated_minutes=2,
        tags=["긴장돼요"],
        allowed_contexts=ALL_CONTEXTS,
    )

    ActivityModuleTemplate.objects.create(
        content_type="stretch_guide",
        title="눈에 띄지 않는 목 리셋",
        description="자리에서 티 나지 않게 따라 할 수 있는 목·어깨 스트레칭입니다.",
        steps=[
            {"order": 1, "instruction": "어깨를 귀에서 멀어지게 내립니다. 그 상태에서 20초간 유지하세요.", "duration_seconds": 20},
            {"order": 2, "instruction": "고개를 천천히 좌우로 기울여 목 옆쪽을 늘려주세요.", "duration_seconds": 20},
            {"order": 3, "instruction": "양손으로 어깨를 감싸고 원을 그리듯 돌려주세요.", "duration_seconds": 20},
        ],
        voice_script="다음 동작으로 넘어갈게요.",
        estimated_minutes=3,
        tags=["몸이 뻐근해요"],
        allowed_contexts=["카페", "기타"],
    )

    ActivityModuleTemplate.objects.create(
        content_type="reflection",
        title="친구를 만나기 전, 마음 정리",
        description="약속 전 지금 기분을 짧게 정리해보는 질문입니다.",
        question="지금 내 기분을 한 단어로 표현하면?",
        question_options=["피곤함", "설렘", "무덤덤함", "긴장됨"],
        allow_text_input=True,
        estimated_minutes=3,
        tags=["긴장돼요", "복잡해요"],
        allowed_contexts=ALL_CONTEXTS,
    )

    ActivityModuleTemplate.objects.create(
        content_type="skin_check",
        title="오늘 피부 컨디션 체크",
        description="물 한 모금을 마시고, 턱에 들어간 힘을 30초 동안 천천히 내려놓아 보세요.",
        question="지금 피부 컨디션은 어떤가요?",
        question_options=["건조해요", "칙칙해요", "괜찮아요"],
        estimated_minutes=2,
        tags=["피부가 신경 쓰여요"],
        allowed_contexts=ALL_CONTEXTS,
    )


def remove_activity_module_templates(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")
    ActivityModuleTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0016_activity_modules'),
    ]

    operations = [
        migrations.RunPython(
            create_activity_module_templates,
            remove_activity_module_templates,
        ),
    ]
