# Generated by Django 6.1 on 2026-08-17
# 실제 화면 문구·선택지로 질문/옵션 재시딩

from django.db import migrations


def align_questions_with_actual_ui(apps, schema_editor):
    Question = apps.get_model("teumteum", "Question")
    Option = apps.get_model("teumteum", "Option")

    # 기존 질문/선택지를 모두 지우고 화면과 동일하게 다시 만든다.
    Question.objects.all().delete()

    # 1번 질문: 장소
    q1 = Question.objects.create(
        question_id=1,
        title="지금 어디에 있나요?",
        description="현재 장소에서 부담 없이 할 수 있는 활동을 골라드릴게요."
    )
    Option.objects.create(option_id=1, question=q1, content="이동 중")
    Option.objects.create(option_id=2, question=q1, content="카페·실내")
    Option.objects.create(option_id=3, question=q1, content="학교·회사")
    Option.objects.create(option_id=4, question=q1, content="집")
    Option.objects.create(option_id=5, question=q1, content="기타")

    # 2번 질문: 회복 방식
    q2 = Question.objects.create(
        question_id=2,
        title="어떤 회복이 필요한가요?",
        description="원하는 방식을 반영해 나만의 틈 코스를 만들게요."
    )
    Option.objects.create(option_id=6, question=q2, content="읽기")
    Option.objects.create(option_id=7, question=q2, content="듣기")
    Option.objects.create(option_id=8, question=q2, content="스트레칭")
    Option.objects.create(option_id=9, question=q2, content="마음 정리")

    # 3번 질문: 다음 일정
    q3 = Question.objects.create(
        question_id=3,
        title="이 틈이 끝나면 무엇을 하나요?",
        description="다음 일정까지 자연스럽게 이어지도록 코스를 구성할게요."
    )
    Option.objects.create(option_id=10, question=q3, content="수업·회의")
    Option.objects.create(option_id=11, question=q3, content="친구·약속")
    Option.objects.create(option_id=12, question=q3, content="업무·과제")
    Option.objects.create(option_id=13, question=q3, content="귀가·휴식")
    Option.objects.create(option_id=14, question=q3, content="없음")
    Option.objects.create(option_id=15, question=q3, content="기타")

    # 4번 질문: 현재 상태
    q4 = Question.objects.create(
        question_id=4,
        title="지금 가장 가까운 상태는?",
        description="지금 필요한 회복에 조금 더 집중해볼게요."
    )
    Option.objects.create(option_id=16, question=q4, content="피곤해요")
    Option.objects.create(option_id=17, question=q4, content="긴장돼요")
    Option.objects.create(option_id=18, question=q4, content="머릿속이 복잡해요")
    Option.objects.create(option_id=19, question=q4, content="몸이 뻐근해요")
    Option.objects.create(option_id=20, question=q4, content="피부가 신경 쓰여요")


def reverse_noop(apps, schema_editor):
    # 이전 시드 데이터 복원은 의미가 없으므로 별도 롤백 없음
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0017_seed_activity_module_templates'),
    ]

    operations = [
        migrations.RunPython(
            align_questions_with_actual_ui,
            reverse_noop,
        ),
    ]
