# Generated by Django 6.1 on 2026-08-17
# 장소 옵션 라벨 변경에 맞춰 활동 모듈 allowed_contexts 갱신

from django.db import migrations

ALL_CONTEXTS = ["이동 중", "카페·실내", "학교·회사", "집", "기타"]
INDOOR_CONTEXTS = ["카페·실내", "학교·회사", "집", "기타"]


def update_allowed_contexts(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")

    ActivityModuleTemplate.objects.filter(
        title="2분 눈·호흡 리셋"
    ).update(allowed_contexts=ALL_CONTEXTS)

    ActivityModuleTemplate.objects.filter(
        title="약속 전 긴장 리셋"
    ).update(allowed_contexts=ALL_CONTEXTS)

    ActivityModuleTemplate.objects.filter(
        title="눈에 띄지 않는 목 리셋"
    ).update(allowed_contexts=INDOOR_CONTEXTS)

    ActivityModuleTemplate.objects.filter(
        title="친구를 만나기 전, 마음 정리"
    ).update(allowed_contexts=ALL_CONTEXTS)

    ActivityModuleTemplate.objects.filter(
        title="오늘 피부 컨디션 체크"
    ).update(allowed_contexts=ALL_CONTEXTS)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0018_align_questions_with_actual_ui'),
    ]

    operations = [
        migrations.RunPython(
            update_allowed_contexts,
            reverse_noop,
        ),
    ]
